[package]
name = "HydraBSA"
version = "0.0.1"
edition = "2024.beta"

[dependencies]

Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
std = "0x1"
sui = "0x2"
default = "0x0"